---
- hosts: all
  connection: ssh
  user: root
  tasks: 
    - name: install httpd & restart
      action: yum name=httpd state=present
      notify: restart httpd
  handlers:
    - name: restart httpd
      action: service name=httpd state=restarted    
