---
- hosts: all
  connection: ssh
  user: root
  tasks:
    - name: create multiple users
      user: name='{{item}}' state=present
      with_items:
              - vamsi
              - wildfire
              - holika
              - shiva
