download_url: https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/artifacts/karcadia-aws-0.0.6.tar.gz
format_version: 1.0.0
name: aws
namespace: karcadia
server: https://galaxy.ansible.com/api/
signatures: []
version: 0.0.6
version_url: /api/v3/plugin/ansible/content/published/collections/index/karcadia/aws/versions/0.0.6/
