- name: Create EC2 instances
  amazon.aws.ec2_instance:
    name: ansibleinstance2
    key_name: "kopskey"
    instance_type: t3.micro
    security_group: default
    region: us-east-1
    aws_access_key: "{{ec2_access_key}}"  # From vault as defined
    aws_secret_key: "{{ec2_secret_key}}"  # From vault as defined      
    network:
      assign_public_ip: true
    image_id: ami-0de716d6197524dd9
      

